# Generated by Django 5.1.6 on 2025-04-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='desciption',
            new_name='description',
        ),
    ]
