# Generated by Django 5.1.6 on 2025-04-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_skill_moon_alter_skill_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
