# Generated by Django 5.1.6 on 2025-05-14 19:17

import base.utils
import django.db.models.deletion
import django.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_exceptiontrace_error_message_and_more'),
        ('profiles', '0004_rename_workhistory_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileskill',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profileskill',
            name='skill',
        ),
        migrations.AddField(
            model_name='profileskill',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SkillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True)),
                ('application_id', models.CharField(editable=False, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('profile_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_skill', to='profiles.profileskill')),
                ('skill', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, related_name='user_profile_skill', to='base.skill')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مهارت های پروفایل',
                'verbose_name_plural': 'مهارت های پروفایل',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
