FROM golang:1.22.2 AS builder

WORKDIR /go/app
COPY golang-server/ .  
RUN go mod download
RUN go build -o main

FROM alpine:latest
WORKDIR /go/app
COPY --from=builder /go/app/main .
CMD ["/go/app/main"]
