version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile.django
    image: alirg1999/django-service:latest
    env_file:
      - ./django-server/.env
    volumes:
      - ./django-server/media/media/:/django/app/media
    network_mode: "host"
    
  golang:
    build:
      context: .
      dockerfile: ./Dockerfile.golang
    image: alirg1999/golang-service:latest
    env_file:
      - ./golang-server/.env
    network_mode: "host"
    depends_on:
      - django

  # nextjs:
  #   build:
  #     context: ../jeraghe-client
  #     dockerfile: Dockerfile
  #   image: alirg1999/nextjs-client:latest
  #   env_file:
  #     - ../jeraghe-client/.env.local
  #   network_mode: "host"
  #   volumes:
  #     - ./jeraghe-client:/app
  #     - /app/node_modules 
  #   environment:
  #     - NODE_ENV=development
  #   restart: unless-stopped
  #   depends_on:
  #     - django
  #     - golang
