FROM golang:1.22.2 AS builder

WORKDIR /go/app

COPY golang-server/go.mod .
COPY golang-server/go.sum .

ENV GOPROXY=direct

RUN go mod download

COPY golang-server/ .

RUN go build -o main .

CMD ["./main"]
