version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    env_file:
      - ./django-server/.env
    volumes:
      - ./django-server:/django/app
      - ./django-server/media:/app/media
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:172.17.255.255"

  golang:
    build:
      context: .
      dockerfile: Dockerfile.golang
    env_file:
      - ./golang-server/.env
    ports:
      - "8080:8080"
    depends_on:
      - django
    extra_hosts:
      - "host.docker.internal:172.17.255.255"
