version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile.django
    image: alirg1999/django-service:latest
    env_file:
      - ./django-server/.env
    volumes:
      - ./django-server:/django/app
      - ./django-server/media:/app/media
    network_mode: "host"
    
  golang:
    build:
      context: .
      dockerfile: ./Dockerfile.golang
    image: alirg1999/golang-service:latest
    env_file:
      - ./golang-server/.env
    network_mode: "host"
    depends_on:
      - django
