version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - ./django-server:/django/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:admin@host.docker.internal:5432/jeraghe
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    extra_hosts:
      - "host.docker.internal:host-gateway"

  golang:
    build:
      context: .
      dockerfile: Dockerfile.golang
    ports:
      - "8080:8000"
    environment:
      - DJANGO_API=http://django:8000/api
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
    depends_on:
      - django
    extra_hosts:
      - "host.docker.internal:host-gateway"
