# Generated by Django 5.1.6 on 2025-04-18 09:55

import base.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True)),
                ('application_id', models.CharField(editable=False, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='idea/idea_images/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('idea', 'ایده خام'), ('development', 'در حال توسعه'), ('prototype', 'نمونه اولیه'), ('funding', 'در حال جذب سرمایه')], default='idea', max_length=50, verbose_name='وضعیت فعلی ایده')),
                ('needs_collaborators', models.BooleanField(verbose_name='نیاز به همکار داری؟')),
                ('collaboration_type', models.CharField(blank=True, choices=[('full_time', 'تمام\u200cوقت'), ('part_time', 'پاره\u200cوقت'), ('consultant', 'مشاوره\u200cای'), ('participatory', 'مشارکتی')], max_length=50, null=True, verbose_name='نحوه همکاری')),
                ('related_files', models.FileField(blank=True, null=True, upload_to='idea/idea_files/%Y/%m/%d/', verbose_name='فایل\u200cهای مرتبط')),
                ('repo_url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='idea_category', to='base.category')),
                ('contact_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.contact')),
            ],
            options={
                'verbose_name': 'ایده',
                'verbose_name_plural': 'ایده\u200cها',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
