# Generated by Django 5.1.6 on 2025-04-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='image',
        ),
        migrations.AddField(
            model_name='idea',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea/idea_images/logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='idea',
            name='log_image',
            field=models.ImageField(blank=True, null=True, upload_to='idea/idea_images/banner/%Y/%m/%d/'),
        ),
    ]
