# Generated by Django 5.1.6 on 2025-04-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_initial'),
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='readme_content',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='related_links',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='required_skills',
        ),
        migrations.AddField(
            model_name='idea',
            name='required_skills',
            field=models.ManyToManyField(related_name='required_skills', to='profiles.skill'),
        ),
    ]
