# Generated by Django 5.1.6 on 2025-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_remove_idea_image_idea_banner_image_idea_log_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
