# Generated by Django 5.1.6 on 2025-04-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_alter_idea_image_alter_idea_related_files'),
        ('profiles', '0004_delete_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='required_skills',
            field=models.ManyToManyField(related_name='required_skills', to='profiles.skill', verbose_name='مهارت های مورد نیاز'),
        ),
    ]
