# Generated by Django 5.1.6 on 2025-04-18 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tokenlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenLog',
        ),
    ]
