# Generated by Django 5.1.7 on 2025-03-28 18:43

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the object is active or soft-deleted')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی\u200cها',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the object is active or soft-deleted')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
