# Generated by Django 5.1.6 on 2025-04-18 09:55

import base.utils
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True)),
                ('application_id', models.CharField(editable=False, max_length=255)),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی\u200cها',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True)),
                ('application_id', models.CharField(editable=False, max_length=255)),
                ('platform', models.CharField(max_length=20, verbose_name='شبکه اجتماعی')),
                ('link', models.CharField(max_length=255, verbose_name='نام کاربری یا لینک')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده؟')),
            ],
            options={
                'verbose_name': 'اطلاعات تماس شبکه اجتماعی',
                'verbose_name_plural': 'اطلاعات تماس شبکه\u200cهای اجتماعی',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExceptionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('path', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('error_message', models.TextField()),
                ('stack_trace', models.TextField(blank=True, null=True)),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('is_from_gateway', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'exception_traces',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True)),
                ('application_id', models.CharField(editable=False, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('moon', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'مهارت های کاربر',
                'verbose_name_plural': 'مهارت های کاربر',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True)),
                ('application_id', models.CharField(editable=False, max_length=255)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
