# Generated by Django 5.1.6 on 2025-04-10 17:30

import base.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.SlugField(blank=True, default=base.utils.generate_unique_id, editable=False, help_text='Unique identifier for the object', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of object creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the object is active or soft-deleted')),
                ('platform', models.CharField(max_length=20, verbose_name='شبکه اجتماعی')),
                ('link', models.CharField(max_length=255, verbose_name='نام کاربری یا لینک')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده؟')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اطلاعات تماس شبکه اجتماعی',
                'verbose_name_plural': 'اطلاعات تماس شبکه\u200cهای اجتماعی',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
