# Generated by Django 5.1.6 on 2025-04-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='description',
        ),
    ]
