# Generated by Django 5.1.6 on 2025-03-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_tags_options_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
