# Generated by Django 5.1.6 on 2025-05-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_category_deleted_at_contact_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='moon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='year',
        ),
    ]
