name: Django + Go CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  django:
    name: Django Check 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        working-directory: django-server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Check 
        run: |
          python manage.py check

  golang:
    name: Go Check 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22 

      - name: Install Go Modules
        working-directory: golang-server
        run: |
          go mod tidy

      - name: Run Go Check
        run: |
          go vet ./...
          go build ./...
